name: condaenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - dash=2.11.1
  - flask-compress=1.13
  - dash-extensions=1.0.1
  - orjson=3.9.2
  - dash-bio=1.0.2
  - pandas=2.0.3
  - pyarrow=12.0.1
  - networkx=3.1
  - anndata=0.8.0
  - scanpy=1.9.3
  - numpy=1.23.1
  - scipy=1.11.1
  - matplotlib=3.7.2
  - celery=5.3.1
  - redis-py=4.6.0
  - dash-bootstrap-components=1.4.2
  - fastwsgi
  # Below are only needed for diskcache local caching, in deployment we use redis
  #- diskcache=5.6.1
  #- multiprocess=0.70.13
  #- psutil=5.9.5
  #- dill=0.3.6
  #- pip:
      #- kaleido==0.2.1