name: condaenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - dash=2.9.1
  - flask-compress=1.13
  - dash-extensions=1.0.0
  - orjson=3.8.2
  - dash-bio=1.0.2
  - pandas=1.5.2
  - pyarrow=10.0.1
  - networkx=2.8.8
  - anndata=0.8.0
  - scanpy=1.9.1
  - numpy=1.23.1
  - scipy=1.9.3
  - matplotlib=3.6.2
  - celery=5.2.7
  - redis-py=4.3.4
  - dash-bootstrap-components=1.4.2
  - fastwsgi
  # Below are only needed for diskcache local caching, in deployment we use redis
  #- diskcache=5.4.0
  #- multiprocess=0.70.12.2
  #- psutil=5.9.4
  #- dill=0.3.4
  #- pip:
      #- kaleido==0.2.1